### ISSUE TITLE
Change Price Model Suggestion

### ISSUE THREAD

**Issue by nimzoking** [justdjango/django-ecommerce#2]
Hi Matt,

Think it would make sense to change the model for the pricing elements to DecimalField, the use of Float messes up with the calculations of the discounts.

I have changed core/models.py for the time being to:

price = models.DecimalField(max_digits=5,decimal_places=2)
discount_price = models.DecimalField(max_digits=5,decimal_places=2)

Works much better from a currency / pricing perspective.

Tilly.

**Comment by justdjango** [comment]
This sounds reasonable. Out of interest can you provide an example where the calculations are not accurate?
