### ISSUE TITLE
launching a django project from with help of visual studio

### ISSUE THREAD

**Issue by user-test-2020** [justdjango/django-ecommerce#26]
Hi,

Thanks for codes and videos.

I have a question about launching a project from a github on my computer.

I downloaded this project. Using Visual Studio, first created a new project from existing code, then added the environment (according to the requirements file). But when I start the server, such an error is issued.
![django](https://user-images.githubusercontent.com/63072242/78293608-8006d480-7531-11ea-8303-a0b8a2994314.png)

Could you please advise what I'm doing wrong.

**Comment by shrey1608** [comment]
After adding the environment run ``` python manage.py makemigrations ``` and then run ``` python manage.py migrate ``` and then ``` pip install requirements.txt ``` and then run the server. Hope this helps!

**Comment by mattfreire** [comment]
Please post questions like this on StackOverflow. The point of GitHub issues is to keep track of the issues with code in this project.
