### ISSUE TITLE
Item stock not defined in the Item model

### ISSUE THREAD

**Issue by Duke09** [justdjango/django-ecommerce#27]
We never defined an item_stock field to the Item model. Since Order has a quantity field, to store how many unit of that item we want. But we never defined that in the Item model. I tried adding the item stock field, but the issue here is, I am not able to decrease the quantity of that item stock after an order is placed. Please help

**Comment by mnuckingfutz** [comment]
I know, I tried to do so but problem is orderitem has many orders placed so it says in terminal multiple querysets returned....if you were able to solve this pls tell me how!!
