### ISSUE TITLE
ImportError: cannot import name 'config' from 'decouple'

### ISSUE THREAD

**Issue by guptanaman40** [justdjango/django-ecommerce#32]

**Comment by Sanjay157** [comment]
Hi @guptanaman40 
Firstly install all module at once i.e., whatever is in requirements file through this command hope this will help **pip install -r requirements.txt**

**Comment by OvoidChickenStorage** [comment]
I agree with @Sanjay157. Import errors are generally caused by an mis-configured environment try navigating to the area where you git cloned the project and running the `pip install -r requirements.txt`   and if it works you should set up a virtual environment as it is best practice

**Comment by AineasGamingYolo** [comment]
pip uninstall decouple then pip install python-decouple
ive had the same issue, spend almost 30days on that problem lmao. Good luck on your journey,

**Comment by Sanjay157** [comment]
@AineasGamingYolo If it's only for **decouple** module, you can go ahead with this suggestion. Even after running this command people might find difficulty with other modules. So maintaining a **requirement.txt** file for their code is the best practice any developer can have, hence others can follow along with the project.

**Comment by oyerohabib** [comment]
i also have same problem.
the requirement.txt file came with python -decouple.
after installing requirement.txt, it brings error no module named decouple.
then i did pip install decouple and it producec error "cannot import name 'config' from 'decouple'".

**Comment by sheshomaru28** [comment]
I pip install decouple and pip -r requirements.txt in where the text files in my virtual environment. I checked within the decouple module dir and I didn't find the config method...

**Comment by mattfreire** [comment]
Seems like this is resolved so closing.
