### ISSUE TITLE
Rename command issue

### ISSUE THREAD

**Issue by OvoidChickenStorage** [justdjango/django-ecommerce#35]
Rename command looks for `projectname/settings.py` but `settings.py` has been depreciated for `settings/base.py`.

Can be fixed by changing `core/management/commands/rename.py` from:

        files_to_rename = [f'{current_project_name}/settings.py',
                          f'{current_project_name}/wsgi.py', 'manage.py']
To:

        files_to_rename = [f'{current_project_name}/settings/base.py',
                           f'{current_project_name}/wsgi.py', 'manage.py']

**Comment by csyjin6** [comment]
thanks man

**Comment by mattfreire** [comment]
Fixed in [this PR](https://github.com/justdjango/django-ecommerce/pull/28)
