### ISSUE TITLE
manage.py rename function will not rename

### ISSUE THREAD

**Issue by shendsaliaga** [justdjango/django-ecommerce#6]
The function rename is hardcoded to the project folder name 'demo', however, in this case, it is named 'djecommerce'. I solved this by changing the function to use 'djecommerce' instead of 'demo' so I would initially be able to change the name of the project. However, in the future renaming would require the function to be edited again to whatever the current project name is.

**Comment by mattfreire** [comment]
Fixed this in the latest commit. Instead now you pass the current project name and new project name as arguments

**Comment by kolaveridi** [comment]
yes  running python manage.py rename demo djecommerece worked

**Comment by raikk** [comment]
It worked
`python manage.py rename demo djecommerece`

but there is no djecommerece/Setting directory in it.
as well base.py file is not there after rename

**Comment by Tim-py-coder** [comment]
> It worked
> `python manage.py rename demo djecommerece`
> 
> but there is no djecommerece/Setting directory in it.
> as well base.py file is not there after rename

**Comment by sirkays** [comment]
it did not work, displaying error: No module named 'djecommerce'

**Comment by ckhera7** [comment]
Same error

**Comment by shiva5149** [comment]
> > It worked
> > `python manage.py rename demo djecommerece`
> > but there is no djecommerece/Setting directory in it.
> > as well base.py file is not there after rename

 python3 manage.py rename djecommerce ecommerce
worked fro me

first mention default app name and later your new name to rename successfully

**Comment by SaurabhBagade** [comment]
Can't rename the demo file?
ModuleNotFoundError: No module named 'djecommerce'

**Comment by TUTI254** [comment]
oh so in order for it to rename the  file 

`python manage.py rename  djecommerece  newfilename`

depending on current file name also add it to the code before adding the new name

**Comment by he-is-right** [comment]
Good day Collins
My name is Timothy Dawadakpoye
Please I would need your help
am trying to add data to my django project using the admin page but am
getting this error

'__str__ returned non-string (type tuple)'
