### ISSUE TITLE
Sign-Up Error: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by sid741994** [justdjango/django-ecommerce#62]
New Signup entries are made on the database, but it displays this error in the browser on clicking submit.
@mattfreire 

![image](https://user-images.githubusercontent.com/19549285/98437590-63ef9500-2109-11eb-8fbb-4ee62f7c2cd4.png)

**Comment by drayendorff** [comment]
This happens because the email  backen cant issue the confimation email 

Add this to the development.py 

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

**Comment by drayendorff** [comment]
Im currently developing on this repo add me on Facebook so we can exchange some more advanced code

**Comment by brahim024** [comment]
you need to add email backend in your settings
check this artical:
https://docs.djangoproject.com/en/3.1/topics/email/

**Comment by sid741994** [comment]
Will do.

**Comment by sid741994** [comment]
Thanks
